#! /bin/sh

rm -r /etc/letsencrypt/live/api.doctorpricer.co.nz/
rm -r /etc/letsencrypt/live/api.doctorpricer.co.nz-0001/

/usr/bin/certbot certificates
/usr/bin/certbot certonly --non-interactive --agree-tos --email doctorpricernz@gmail.com --standalone -d api.doctorpricer.co.nz